In [9]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
from itertools import combinations
from rapidfuzz import fuzz

In [10]:
seed = 1
filepath_syn = Path(f"../data/synthetic/{seed}")
filepath_gt = Path(f"../data/ground_truth/{seed}")

customers_raw = pd.read_csv(filepath_syn/"customers_raw.csv")
products_raw = pd.read_csv(filepath_syn/"products_raw.csv")
orders_raw = pd.read_csv(filepath_syn/"orders_raw.csv")

customers_clean = pd.read_csv(filepath_gt/"customers_clean.csv")
products_clean = pd.read_csv(filepath_gt/"products_clean.csv")

In [11]:
def show_all(df, name=""):
    with pd.option_context("display.max_rows", None,
                           "display.max_columns", None,
                           "display.width", None):
        if name:
            print(f"=== {name}: {len(df)} rows ===")
        display(df)


def inspect_duplicates(df, subset=None, name=""):
    dups = df[df.duplicated(subset=subset, keep=False)]
    sort_cols = subset if subset else list(df.columns)
    with pd.option_context("display.max_rows", None,
                           "display.max_columns", None):
        print(f"=== {name}: {len(dups)} duplicate rows "
              f"(subset={subset or 'all columns'}) ===")
        display(dups.sort_values(by=sort_cols))

def inspect_fuzzy_duplicates(df, cols=None, exclude=None, threshold=85,
                             scorer=fuzz.ratio, name=""):
    exclude = set(exclude or [])
    if cols is None:                      
        cols = [c for c in df.columns if c not in exclude]
    sub = df[cols].fillna("").astype(str)
    recs = sub.to_dict("records")
    idx = df.index.tolist()

    rows = []
    for a, b in combinations(range(len(df)), 2):
        scores = {c: scorer(recs[a][c], recs[b][c]) for c in cols}
        avg = sum(scores.values()) / len(cols)
        if avg >= threshold:
            rows.append({"score": round(avg, 1), "idx_a": idx[a], "idx_b": idx[b],
                         **{f"{c}_a": recs[a][c] for c in cols},
                         **{f"{c}_b": recs[b][c] for c in cols}})

    result = (pd.DataFrame(rows).sort_values("score", ascending=False)
              .reset_index(drop=True))
    with pd.option_context("display.max_rows", None, "display.max_columns", None):
        print(f"=== {name}: {len(result)} fuzzy pairs "
              f"(threshold={threshold}, cols={cols}) ===")
        display(result)
    return result

In [21]:
# Customers

#show_all(customers_raw.sort_values("customer_id"), "customers_raw")             #sorted raw
#show_all(customers_clean.sort_values("customer_id"), "customers_clean")         #sorted clean
#show_all(customers_raw, "customers_raw")                                        #unsorted
show_all(customers_clean, "customers_clean")                                    #unsorted

# Duplicates

#inspect_duplicates(customers_raw, name="customers_raw")
#inspect_duplicates(customers_clean, name="customers_clean")    # 0 expected

#inspect_fuzzy_duplicates(customers_raw, cols=["full_name", "email"], threshold=80, name="customers_raw");

=== customers_clean: 500 rows ===

,customer_id,full_name,email,country_code,registered_at
0,1,Karsten Wieloch-Bolnbach,erkan77@example.com,CH,2025-07-17
1,2,Rebecca Häring-Dehmel,ybaum@example.com,GB,2025-03-02
2,3,Nico Matthäi,irmtraud39@example.org,AT,2022-09-13
3,4,Aldo Bauer,kranzheidelinde@example.org,IT,2023-08-04
4,5,Jose Hartung,joderwald@example.org,AT,2022-12-10
5,6,Univ.Prof. Emanuel Wesack MBA.,susan06@example.net,BE,2025-06-18
6,7,Dogan Schuchhardt,erol58@example.com,BE,2024-04-26
7,8,Gereon Hölzenbecher MBA.,cschacht@example.com,BE,2022-01-24
8,9,Herlinde Stadelmann-Gerlach,bertha51@example.com,NL,2025-08-24
9,10,Reinhard Fröhlich,fkoch-ii@example.net,FR,2020-04-01
10,11,Frau Franca Tlustek MBA.,gunterpaffrath@example.org,AT,2020-02-08
11,12,Juri Rogge B.A.,wpieper@example.net,BE,2023-01-02
12,13,Therese Heuser B.Sc.,vziegert@example.net,DE,2021-02-05
13,14,Heino Blümel MBA.,catrin83@example.net,NL,2023-07-08
14,15,Ing. Herlinde Kensy B.Sc.,vadim90@example.org,NL,2025-05-28
15,16,Prof. Klaus-Günter Girschner,rohlederlucie@example.com,GB,2020-04-10
16,17,Attila Bachmann,waustermuehle@example.com,DE,2022-02-14
17,18,Barbara Scholz,moritzhoffmann@example.org,BE,2021-06-04
18,19,Ing. Jose Geisler,friederike47@example.net,IT,2022-09-27
19,20,Dipl.-Ing. Beatrix Barth B.Eng.,akarz@example.org,FR,2022-03-13
20,21,Ferdi Vollbrecht,wallyauch-schlauchin@example.com,GB,2020-03-05
21,22,Herr Hans-Ulrich Fiebig B.Sc.,tilmanntlustek@example.net,AT,2025-10-08
22,23,Prof. Sarah Hartmann,hhauffer@example.net,ES,2020-04-05
23,24,Marietta Ruppert-Jungfer,vbonbach@example.com,DE,2021-01-25
24,25,Tassilo Biggen B.Eng.,buchholzlothar@example.com,DE,2021-05-06
25,26,Prof. Elisa Ehlert,roerrichtpriska@example.org,DE,2025-01-08
26,27,Wolfgang Roskoth MBA.,mariolazahn@example.net,PL,2025-04-19
27,28,Hans-Henning Gute,eckart39@example.net,DE,2023-09-07
28,29,Ismet Döhn MBA.,aloisia70@example.com,NL,2025-03-16
29,30,Tatiana Holzapfel-Bähr,hans-willijunken@example.net,FR,2021-02-23
30,31,Hubertine Hamann,gundula16@example.net,NL,2022-12-04
31,32,Prof. Edeltraud Bolzmann B.Sc.,eimerguntram@example.org,DE,2024-07-30
32,33,Frank-Peter Werner B.Eng.,patrik55@example.org,PL,2022-06-23
33,34,Prof. Reinhardt Trubin MBA.,claudiarohleder@example.org,FR,2022-09-23
34,35,Hansjürgen Briemer,jzirme@example.org,BE,2022-11-25
35,36,Leonid Schaaf,kbuchholz@example.net,BE,2021-11-26
36,37,Willy Hethur,rosa49@example.net,PL,2020-12-21
37,38,Tamara Hofmann B.Sc.,huebelaleksandr@example.net,FR,2025-09-13
38,39,Bartholomäus Lehmann,zobelarnulf@example.org,ES,2022-01-14
39,40,Dr. Benita Mende,hanne-lorehendriks@example.org,FR,2020-11-15
40,41,Dipl.-Ing. Rosa-Maria Riehl,bettina47@example.com,FR,2020-11-07
41,42,Massimo Junck B.Sc.,atzlerlilly@example.com,BE,2025-01-27
42,43,Ingried Krein,rochus11@example.com,IT,2025-02-11
43,44,Beate Hermann B.A.,wspeer@example.com,DE,2021-07-23
44,45,Gerhart Gumprich B.A.,danny41@example.com,NL,2020-10-08
45,46,Veronica Heidrich,cjaentsch@example.com,PL,2021-08-03
46,47,Reingard Sager,ismail51@example.net,AT,2025-03-14
47,48,Evangelos Hartmann,henkrolf-peter@example.org,CH,2022-04-12
48,49,Ottokar Bruder,schusteralbin@example.com,IT,2023-01-20
49,50,Dipl.-Ing. Sofie Fliegner B.Sc.,cosimo82@example.org,AT,2021-04-09
50,51,Salvatore Juncken-Jäkel,troestanja@example.net,ES,2022-06-30
51,52,Timm Haering-Faust,zahnmaik@example.net,PL,2025-09-19
52,53,Dietmar Jacob MBA.,benedikttrueb@example.net,NL,2022-02-07
53,54,Philomena Bolnbach,jlosekann@example.com,PL,2024-08-09
54,55,Sigrun Renner MBA.,krokermary@example.com,FR,2021-06-16
55,56,Janin Barth,brudolph@example.org,IT,2025-11-19
56,57,Leopoldine Etzler,frederikheser@example.com,IT,2023-05-20
57,58,Christiane Schmidtke-Cichorius,zeljkoalbers@example.org,GB,2024-06-30
58,59,Jo Seip,ostriebitz@example.net,BE,2021-12-02
59,60,Ing. Ivan Striebitz MBA.,ingridlehmann@example.com,PL,2024-10-07
60,61,Yvette Seidel,benboucsein@example.net,NL,2025-06-27
61,62,Catharina Pergande,ludgerhuhn@example.net,GB,2022-07-19
62,63,Centa Tintzmann,fscheibe@example.org,DE,2025-02-26
63,64,Christl Förster-Hermann,kharloff@example.net,BE,2020-06-10
64,65,Univ.Prof. Heide Trupp B.Eng.,kpieper@example.net,FR,2020-05-06
65,66,Ronny Hermighausen,hethurjenny@example.org,NL,2021-03-08
66,67,Helge Hendriks,zloewer@example.org,NL,2022-10-08
67,68,Bianka Scholtz MBA.,ernst-augustlosekann@example.net,CH,2024-07-17
68,69,Frau Maria Hübel,iwan68@example.org,ES,2021-08-12
69,70,Leonore Bärer B.Sc.,martinahess@example.org,PL,2021-06-21
70,71,Caren Riehl,juergenjockel@example.net,ES,2022-02-18
71,72,Regine Geisler B.Eng.,hlinke@example.org,AT,2024-11-07
72,73,Daniela Hölzenbecher-Dörr,drubincathleen@example.net,BE,2020-02-11
73,74,Wilfriede Steuer,conradotto@example.com,PL,2024-11-13
74,75,Ilse Paffrath,katrin85@example.org,AT,2021-01-19
75,76,Mina Mende B.Eng.,auguste65@example.net,CH,2025-10-24
76,77,Frau Marga Kostolzin MBA.,brigitteadler@example.com,PL,2025-05-28
77,78,Viktor Misicher MBA.,hubertine27@example.net,NL,2025-09-09
78,79,Hans Peter Putz B.Sc.,bsager@example.com,ES,2022-11-09
79,80,Ismet Weinhage,filizseip@example.com,BE,2025-05-10
80,81,Hansjürgen Ullmann,evelinwulff@example.com,DE,2022-04-19
81,82,Herr Rupert Wulf,keudelsiglinde@example.com,BE,2023-07-01
82,83,Carmela Misicher,zbigniew27@example.net,DE,2020-05-21
83,84,Josephine Dippel,wbohnbach@example.org,IT,2025-08-02
84,85,Alexa Gehringer B.A.,kuehnertewa@example.net,GB,2022-05-06
85,86,Deborah Rädel,hueseyinkade@example.com,GB,2020-07-31
86,87,Nicolaus Preiß,volkmar88@example.net,GB,2020-06-03
87,88,Ing. Mathias Wähner,nurettin93@example.com,NL,2024-10-09
88,89,Christiane Nette-Zobel,nuray95@example.net,CH,2021-11-21
89,90,Wibke Schmidt,miaspeer@example.org,CH,2025-04-17
90,91,Frida Löwer-Wesack,lilianeheuser@example.org,PL,2020-08-13
91,92,Prof. Helfried Salz,edeltrauthesse@example.com,FR,2024-06-24
92,93,Dr. Reinhard Etzler,tklingelhoefer@example.com,DE,2022-01-17
93,94,Oscar Haering,cetin13@example.com,FR,2022-09-25
94,95,Frau Waltraud Gotthard B.Sc.,schenkanatolij@example.org,PL,2025-10-23
95,96,Ivan Tlustek,qkarz@example.com,PL,2021-01-01
96,97,Herr Emmerich Kuhl,agathemende@example.com,FR,2021-06-07
97,98,Dr. Sahin Hölzenbecher MBA.,chahn@example.net,NL,2022-03-12
98,99,Jennifer Scheel,hamanndamian@example.org,PL,2020-02-17
99,100,Stavros Naser,ricarda69@example.com,ES,2021-08-31
100,101,Catharina Werner-Seidel,lonibecker@example.org,GB,2023-04-18
101,102,Thaddäus Stadelmann-Riehl,rosemannraik@example.com,ES,2021-02-07
102,103,Herwig Siering,selma00@example.net,BE,2020-07-08
103,104,Amir Höfig-Zahn,loewerdino@example.org,IT,2020-03-26
104,105,Univ.Prof. Birgitta Weinhage B.Eng.,gieselameister@example.com,PL,2022-10-21
105,106,Xenia Heß,isidorbonbach@example.net,GB,2025-01-08
106,107,Ing. Heinz Schleich,kitzmannbernadette@example.com,DE,2024-07-29
107,108,Nurettin Reising MBA.,truebjozef@example.net,NL,2025-03-12
108,109,Fedor Gierschner,flantzbranko@example.org,PL,2023-08-23
109,110,Andrew Schweitzer,peukertwalfried@example.net,CH,2023-02-24
110,111,Gert Benthin,anniebeckmann@example.com,PL,2025-08-25
111,112,Timo Kroker-Wiek,vbarth@example.net,PL,2022-04-18
112,113,Fatih Junk,jacobi-jaeckelapostolos@example.com,FR,2020-06-29
113,114,Frauke Wähner,johannkramer@example.org,NL,2025-10-06
114,115,Antonietta Löffler,almaroht@example.org,DE,2022-10-22
115,116,Josefine Ziegert,esauer@example.org,BE,2021-02-07
116,117,Karolin Römer B.Sc.,josephine23@example.com,ES,2023-04-24
117,118,Ariane Lange,felix91@example.org,GB,2022-07-22
118,119,Herta Huhn,nikolaos45@example.net,PL,2024-06-03
119,120,Jonathan Eberhardt,manfredvogt@example.com,FR,2022-10-14
120,121,Henner Holt,xmetz@example.net,PL,2023-03-28
121,122,Victor Sager,eimerbenedikt@example.net,NL,2024-03-09
122,123,Rahel Henschel,otfried56@example.com,BE,2023-12-14
123,124,Katharina Patberg,angelofinke@example.com,ES,2025-11-05
124,125,Prof. Cemal Dowerg B.A.,nvogt@example.org,NL,2020-11-04
125,126,Michelle Döring,johnboerner@example.net,ES,2024-11-09
126,127,Stanislaus Briemer,francoisegerlach@example.net,DE,2023-09-04
127,128,Klemens Koch,ztroest@example.com,PL,2021-11-14
128,129,Kristian Nohlmans B.A.,rmentzel@example.com,PL,2024-08-18
129,130,Roderich Nerger B.Sc.,rupert30@example.net,GB,2024-07-10
130,131,Juliane Neuschäfer-Buchholz,gschmiedt@example.net,GB,2024-12-21
131,132,Frau Giovanna Mielcarek,grein-grothvictoria@example.com,ES,2025-12-02
132,133,Jurij Dussen van,angelique58@example.net,BE,2024-11-12
133,134,Karoline Langern,oschleich@example.net,GB,2022-08-14
134,135,Felicitas Eigenwillig MBA.,bettinawirth@example.org,DE,2022-02-24
135,136,Heinfried Wähner,kochsiegmar@example.com,FR,2022-05-24
136,137,Tomas Conradi,adolphramon@example.com,CH,2023-12-13
137,138,Renata Zänker,ewa75@example.com,PL,2023-11-18
138,139,Immo Klapp,selimfinke@example.org,GB,2021-06-18
139,140,Gudrun Eckbauer,ulla64@example.net,CH,2022-06-11
140,141,Univ.Prof. Emmi Löwer,leonie73@example.net,AT,2024-03-06
141,142,Milica Löffler-Conradi,ehlertharri@example.org,PL,2021-12-13
142,143,Bernd-Dieter Herrmann,wolf-dieterwohlgemut@example.org,IT,2023-05-25
143,144,Herr Balthasar Loos,rognerheinz-juergen@example.net,DE,2023-08-03
144,145,Angelina Siering,waehnerbirgitt@example.net,AT,2023-07-27
145,146,Franjo Stolze,hans-joerg70@example.org,AT,2025-10-03
146,147,Sven Krebs,staudetimo@example.com,DE,2025-10-19
147,148,Dipl.-Ing. Benita auch Schlauchin MBA.,fischerreginald@example.net,BE,2025-12-22
148,149,Denis Pölitz B.Eng.,iweimer@example.com,DE,2024-03-10
149,150,Richard Werner B.Eng.,adobes@example.net,IT,2025-08-04
150,151,Ursula Trommler,birger87@example.com,FR,2020-11-09
151,152,Prof. Freddy Hiller B.A.,ifinke@example.com,IT,2021-08-29
152,153,Prof. Magarete Scheuermann,reichmannmarta@example.net,AT,2024-05-01
153,154,Wilfried Lehmann-Hiller,wolf-dietrich44@example.com,GB,2021-10-28
154,155,Ing. Lina Möchlichen B.A.,hanns92@example.net,CH,2024-12-08
155,156,Kathi Fischer B.Sc.,annemarie23@example.com,ES,2025-04-18
156,157,Dipl.-Ing. Genoveva Drubin B.A.,hildburghertrampf@example.org,IT,2020-09-30
157,158,Karl-Otto Gerlach,heckercarina@example.org,AT,2024-04-11
158,159,Hildegard Junken,wohlgemutaloys@example.com,CH,2025-03-26
159,160,Herr Pedro Hauffer B.Eng.,julius98@example.com,CH,2020-03-12
160,161,Grzegorz Kensy,enverhermann@example.org,IT,2025-10-17
161,162,Hakan Buchholz,van-der-dussenedward@example.com,PL,2022-09-11
162,163,Ing. Joseph Binner B.Eng.,budigfredi@example.com,CH,2023-03-01
163,164,Herr Milan Jüttner B.Eng.,pieperria@example.com,IT,2020-12-14
164,165,Ulrike Zobel,edeltrauthiller@example.com,IT,2020-10-09
165,166,Prof. Hertha Reising MBA.,roswita34@example.net,BE,2021-02-17
166,167,Kunibert Pechel,gertzilias@example.org,ES,2023-09-12
167,168,Klara Bärer,augusta48@example.com,BE,2024-01-10
168,169,Hans-Wolfgang Trommler-Döhn,christian85@example.net,BE,2024-09-21
169,170,Lorenz Jäntsch,istoll@example.org,AT,2020-08-18
170,171,Mijo Hande-Nette,ottomar42@example.org,DE,2023-04-01
171,172,Helga Drubin B.A.,klemens90@example.net,IT,2020-01-31
172,173,Hans-Herbert Weinhold-Rörricht,miesante@example.com,NL,2025-02-02
173,174,Ing. Valentine Koch II,mlachmann@example.com,ES,2020-06-14
174,175,Hubert Wulff,seidelida@example.net,NL,2020-01-02
175,176,Senol Dörschner,annettepechel@example.com,FR,2024-09-07
176,177,Radmila Rosenow,lydia73@example.net,IT,2022-01-15
177,178,Karl-Ludwig Klemt,ericwulf@example.org,AT,2025-12-27
178,179,Hildegard Vogt,janusz09@example.com,IT,2023-07-13
179,180,Gloria Hornig-Wende,thilo39@example.net,PL,2021-03-24
180,181,Götz Steinberg,peukerth-dieter@example.net,FR,2025-06-19
181,182,Ing. Nuray Tröst B.Sc.,naserrosl@example.org,GB,2023-04-05
182,183,Dipl.-Ing. Orhan Heidrich,heringmicha@example.com,NL,2025-08-02
183,184,Univ.Prof. Herrmann Weimer MBA.,adriane36@example.com,DE,2023-05-24
184,185,Kay-Uwe Neuschäfer,meike22@example.org,FR,2023-03-14
185,186,Frau Resi Bauer,gnatzvalentin@example.com,DE,2025-09-03
186,187,Trude Förster,wilmapruschke@example.org,NL,2022-03-01
187,188,Hinrich Kruschwitz,astatextor@example.com,CH,2020-01-17
188,189,Dipl.-Ing. Udo Freudenberger B.A.,geza31@example.net,DE,2024-09-29
189,190,Dr. Hans-H. Sauer,peukertheinz-guenther@example.com,CH,2022-01-02
190,191,Volkmar Plath,hildegundpaertzelt@example.net,BE,2025-03-16
191,192,Falk Kruschwitz,kdrubin@example.net,PL,2020-05-30
192,193,Anny Römer-Dehmel,hbien@example.org,NL,2020-02-07
193,194,Wladimir Jockel,uholsten@example.com,PL,2021-06-01
194,195,Karl-Ludwig Trommler-Junck,zotto@example.com,FR,2024-09-16
195,196,Univ.Prof. Hans-Rudolf Thanel,fgute@example.com,PL,2023-01-23
196,197,Folker Rosenow-Holt,lidijaullmann@example.net,BE,2020-09-16
197,198,Gerlind Fechner,jens45@example.com,FR,2022-05-17
198,199,Agathe Fischer B.A.,henner31@example.net,PL,2024-07-28
199,200,Jörg-Peter Lorch B.A.,birtemies@example.com,DE,2021-08-31
200,201,Luigi Buchholz,lillistahr@example.org,NL,2020-04-04
201,202,Hannah Lindau-Stoll,danielleschenk@example.org,GB,2025-09-20
202,203,Vinzenz Hendriks,setzold@example.org,ES,2025-08-18
203,204,Gitte Weiß-Gieß,konstantinostroest@example.org,NL,2022-12-16
204,205,Prof. Eveline Cichorius B.Eng.,ilkamitschke@example.org,DE,2022-06-20
205,206,Leonid Köhler,nhermighausen@example.org,IT,2020-06-10
206,207,Catharina Eigenwillig,dowergmonja@example.com,CH,2025-05-21
207,208,Univ.Prof. Edwin Pärtzelt MBA.,trommlerheinfried@example.com,FR,2025-08-15
208,209,Rudolph Trubin-Sager,isabelle01@example.org,DE,2024-10-14
209,210,Maria-Theresia Nerger-Ritter,juanbender@example.net,IT,2021-06-05
210,211,Dipl.-Ing. Yilmaz Höfig MBA.,fheydrich@example.org,AT,2025-09-10
211,212,Domenico Römer-Bachmann,cweller@example.com,AT,2021-10-27
212,213,Rotraut Vollbrecht-Renner,sevim31@example.org,IT,2025-10-07
213,214,Sigmar Löchel,lgraf@example.net,IT,2024-04-08
214,215,Sigmund Pechel MBA.,hans-rainer35@example.net,CH,2024-12-25
215,216,Götz Birnbaum,nbeyer@example.org,NL,2021-04-03
216,217,Isa Beyer,rosemannrobby@example.org,GB,2023-05-27
217,218,Heide Heuser,wenzel08@example.com,IT,2020-02-24
218,219,Ing. Lieschen Weiß,lotte29@example.net,CH,2024-09-22
219,220,Anne-Katrin auch Schlauchin,selim68@example.org,DE,2024-11-23
220,221,Alfred Ruppersberger,ditschlerinsabrina@example.com,PL,2022-11-12
221,222,Nevenka Rohleder,schweitzerpavel@example.net,DE,2020-08-18
222,223,Univ.Prof. Annett Reuter MBA.,alicja80@example.org,GB,2022-10-06
223,224,Dietlind Fiebig,danadoerr@example.com,FR,2022-09-12
224,225,Ing. Gertraude Heß,arnfried13@example.com,GB,2023-05-18
225,226,Lena Zimmer,bruderines@example.org,BE,2022-04-10
226,227,Frau Bianka Holzapfel,horst-guenter31@example.com,CH,2024-02-01
227,228,Paul-Gerhard Peukert,lilo38@example.org,GB,2024-09-07
228,229,Gerti Hübel,arifmargraf@example.com,PL,2020-04-25
229,230,Gino Lindau,renateroht@example.org,DE,2025-01-01
230,231,Dr. Yvonne Gumprich,erdoganschaaf@example.org,NL,2024-12-27
231,232,Oswald Hethur,ygunpf@example.org,FR,2023-01-27
232,233,Gerdi Schmiedecke B.Eng.,stephanieschuster@example.org,ES,2020-02-13
233,234,Frau Cecilia Herrmann B.Sc.,heinkornelia@example.org,AT,2024-06-16
234,235,Herr Wilfried Rädel,hasanmargraf@example.com,FR,2022-01-25
235,236,Prof. Gundi Junk MBA.,gudediana@example.org,GB,2021-08-05
236,237,Waltraud Salz,eschmiedecke@example.com,NL,2020-03-12
237,238,Frau Uta Döhn MBA.,mikhail16@example.org,GB,2025-12-19
238,239,Prof. Kunigunde Speer MBA.,eschleich@example.org,FR,2022-04-13
239,240,Kunigunda Wieloch,iauch-schlauchin@example.com,BE,2022-03-04
240,241,Agnieszka Schleich,zaenkeruwe@example.com,AT,2023-01-09
241,242,Prof. Helfried Häring MBA.,herma26@example.com,NL,2020-06-17
242,243,Hans Georg Ziegert,hermighausenkaroline@example.net,IT,2020-06-16
243,244,Gülten Austermühle,mijo49@example.org,PL,2021-10-09
244,245,Gregor Dussen van,eckbauerlidwina@example.net,BE,2022-07-03
245,246,Prof. Gertraud Heintze,seiferthildegund@example.net,DE,2021-07-22
246,247,Felicitas Hornig,hlinke@example.com,ES,2020-08-18
247,248,Hanspeter Heinrich B.Sc.,ettahauffer@example.org,GB,2023-05-11
248,249,Denise Scholtz-Flantz,judith50@example.net,NL,2025-12-28
249,250,Ingeborg Oestrovsky,gunhildfiebig@example.org,IT,2023-02-25
250,251,Prof. Gertraut Peukert,mjunck@example.org,DE,2024-12-18
251,252,Rose Rogge,stefan04@example.org,CH,2025-06-07
252,253,Frau Joana Hartmann B.Eng.,ykoehler@example.org,FR,2020-06-17
253,254,Kornelius Pieper,folkerhornich@example.org,ES,2020-07-31
254,255,Abraham Steinberg B.Sc.,twagenknecht@example.org,GB,2020-07-24
255,256,Adelbert Beer,meik09@example.org,CH,2024-10-02
256,257,Horst-Günter Gute B.Eng.,constance88@example.com,ES,2021-12-26
257,258,Dr. Hans-Michael Bonbach,wibkeroehricht@example.net,NL,2023-11-07
258,259,Guenther Junken,bdussen-van@example.net,FR,2021-07-28
259,260,Rainer Gorlitz,helmuthgierschner@example.com,IT,2020-10-30
260,261,Roberto Johann,calogeromargraf@example.org,AT,2021-12-18
261,262,Peter-Michael Hörle,boris91@example.com,NL,2021-09-14
262,263,Univ.Prof. Dittmar Dussen van B.Sc.,bernwardweinhold@example.net,PL,2020-12-26
263,264,Willy Zimmer,tatianahoerle@example.net,ES,2022-02-22
264,265,Dr. Miriam Beckmann,kornelia35@example.com,PL,2023-01-14
265,266,Ortrud Sorgatz MBA.,bcichorius@example.org,BE,2024-02-29
266,267,Theresia Gieß,henckclaudius@example.com,PL,2022-05-10
267,268,Tülay Käster,sabri75@example.com,FR,2022-09-08
268,269,Wanda Mude-Pergande,koch-iiferdinand@example.com,AT,2021-06-06
269,270,Käthi Eberth,guiseppemielcarek@example.net,DE,2025-05-02
270,271,Cengiz Fritsch-Budig,hubert55@example.org,AT,2022-05-11
271,272,Ing. Anneliese Lorch B.A.,renata71@example.org,CH,2025-10-27
272,273,Annedore Stolze,wolf-dieterreinhardt@example.org,CH,2020-05-25
273,274,Martin Klemm B.Eng.,nancy85@example.com,CH,2025-07-25
274,275,Dittmar Kohl,hillerreinhild@example.net,PL,2021-10-14
275,276,Fabian Jähn,carina63@example.com,FR,2020-06-02
276,277,Ing. Nicolas Roskoth B.Sc.,dusanernst@example.org,IT,2023-02-20
277,278,Britta Fröhlich,constantinjockel@example.net,ES,2024-05-05
278,279,Dipl.-Ing. Leyla Peukert,ggnatz@example.com,GB,2021-08-30
279,280,Frau Erica Haering,klaerefaust@example.org,PL,2021-10-09
280,281,Darius Neureuther,hans-eberhard05@example.org,IT,2025-03-09
281,282,Univ.Prof. Nico Hahn B.Sc.,pseifert@example.org,ES,2025-02-12
282,283,Cecilia Ruppert,harloffmaik@example.com,ES,2024-09-11
283,284,Tomislav Birnbaum,alicia85@example.org,ES,2024-02-25
284,285,Jens-Peter Juncken,edelgard59@example.org,AT,2024-02-03
285,286,Herma Boucsein,calogero50@example.org,IT,2022-10-14
286,287,Ing. Francis Herrmann B.Eng.,aliebelt@example.com,FR,2021-05-19
287,288,Angelique Drub,nlosekann@example.org,GB,2022-05-14
288,289,Pamela Söding,sruppert@example.net,BE,2022-03-06
289,290,Ing. Claas Kitzmann,kruschwitzolaf@example.net,CH,2024-10-27
290,291,Hans-Theo Mende B.A.,pthanel@example.org,GB,2025-06-10
291,292,Herr Pavel Boucsein B.Sc.,eroskoth@example.net,PL,2022-10-13
292,293,Prof. Nils Oestrovsky,yaumann@example.net,AT,2024-10-12
293,294,Centa Scheel B.Eng.,van-der-dussenpaul@example.com,ES,2023-09-22
294,295,Univ.Prof. Mariusz Spieß B.Eng.,margrafkatja@example.com,DE,2021-08-29
295,296,Dr. Heinz-Wilhelm Bien,caroline52@example.net,NL,2024-03-03
296,297,Frau Leni Heintze B.Sc.,ksoelzer@example.net,AT,2021-10-09
297,298,Irmtraud Ebert-Jopich,frederik25@example.org,NL,2021-07-14
298,299,Edelgard Röhrdanz,dmosemann@example.net,CH,2024-09-11
299,300,Christa-Maria Pölitz,daria34@example.net,CH,2021-04-25
300,301,Rudolf Karge,loefflerraimund@example.net,ES,2025-07-27
301,302,Prof. Tibor Mans,creinhardt@example.com,AT,2021-10-03
302,303,Augustin Ullmann,dietzastrid@example.com,GB,2021-03-02
303,304,Heidelore Gnatz MBA.,lpreiss@example.org,GB,2024-12-29
304,305,Wilhelm Schäfer MBA.,skrebs@example.com,NL,2021-06-23
305,306,Claire Wulf,roehrichtburghard@example.net,AT,2020-07-20
306,307,Dipl.-Ing. Silvio Juncken MBA.,ricarda16@example.org,GB,2023-12-25
307,308,Uta Lange,gkabus@example.org,PL,2021-05-25

In [13]:
# Products

show_all(products_raw.sort_values("product_id"), "products_raw")     #sorted
show_all(products_clean.sort_values("product_id"), "products_clean") 
#show_all(products, "products")                               #unsorted

# Duplicates

inspect_duplicates(products_raw, name="products_raw")
#inspect_duplicates(products_clean, subset=["product_id"], name="products_clean")

=== products_raw: 100 rows ===

,product_id,name,category,price_eur,in_stock
0,1,Object-based explicit attitude,Clothing,134.94 EUR,yes
1,2,Configurable upward-trending complexity,Clothing,€498.06,1
2,3,Triple-buffered global hierarchy,Books,€346.33,true
3,4,Re-contextualized interactive strategy,Electronics,394.82,1
4,5,Multi-tiered bottom-line implementation,Sports,433.18 EUR,no
5,6,Business-focused intermediate portal,Home,324.49,1
6,7,Exclusive bifurcated emulation,Toys,€314.29,1
7,8,Team-oriented mission-critical info-mediaries,Clothing,53.69,true
8,9,Enhanced systemic challenge,Sports,62.39,true
9,10,Face-to-face regional attitude,Toys,"323,37",1
10,11,Team-oriented grid-enabled Graphic Interface,Sports,219.44 EUR,true
11,12,Profit-focused leadingedge workforce,Home,"419,41",false
12,13,Visionary composite implementation,Home,472.95 EUR,false
13,14,Self-enabling mission-critical open system,Books,35.02 EUR,true
14,15,Enterprise-wide 5thgeneration middleware,Home,"321,07",1
15,16,Exclusive systemic encryption,Clothing,"242,00",true
16,17,Virtual clear-thinking capability,Sports,415.80 EUR,false
17,18,Grass-roots next generation access,Books,€282.80,true
18,19,Adaptive holistic forecast,Clothing,€471.99,true
19,20,Extended actuating function,Electronics,282.96 EUR,1
20,21,Switchable systematic circuit,Electronics,"386,29",yes
21,22,De-engineered asymmetric structure,Electronics,€145.63,yes
22,23,Diverse optimizing instruction set,Home,354.09,yes
23,24,Future-proofed well-modulated workforce,Home,293.44 EUR,0
24,25,De-engineered asynchronous core,Sports,485.40,true
25,26,Virtual cohesive portal,Books,257.15,true
26,27,Operative didactic toolset,Electronics,208.22,0
27,28,Object-based needs-based matrix,Toys,"24,64",true
28,29,Enhanced real-time architecture,Clothing,307.34,yes
29,30,Proactive dynamic database,Electronics,"38,84",1
30,31,Compatible systemic collaboration,Sports,"156,82",yes
31,32,Fully-configurable content-based pricing struc...,Sports,"237,94",yes
32,33,Seamless tangible circuit,Clothing,"428,83",false
33,34,Reactive empowering architecture,Toys,180.82 EUR,1
34,35,Visionary web-enabled orchestration,Clothing,"303,49",yes
35,36,Multi-layered attitude-oriented help-desk,Toys,387.28 EUR,1
36,37,Progressive even-keeled conglomeration,Clothing,416.57 EUR,true
37,38,Switchable non-volatile leverage,Clothing,€295.97,1
38,39,Optional zero tolerance open architecture,Clothing,437.34,1
39,40,Re-engineered tertiary open architecture,Books,486.29 EUR,1
40,41,Face-to-face clear-thinking neural-net,Electronics,"133,52",yes
41,42,Reverse-engineered bottom-line utilization,Books,408.18,1
42,43,Optional user-facing interface,Sports,41.64 EUR,1
43,44,Multi-layered directional intranet,Toys,€109.46,false
44,45,Synergistic next generation infrastructure,Books,€203.36,false
45,46,Managed static open system,Clothing,387.09 EUR,yes
46,47,Enterprise-wide actuating throughput,Clothing,"258,20",1
47,48,Business-focused holistic process improvement,Home,"171,57",no
48,49,Persistent cohesive protocol,Books,64.31,1
49,50,Up-sized maximized orchestration,Sports,€231.90,1
50,51,Multi-layered heuristic collaboration,Books,231.79,1
51,52,Persevering dedicated moratorium,Books,€12.68,yes
52,53,Polarized national forecast,Sports,€305.19,yes
53,54,Right-sized demand-driven capacity,Clothing,€460.66,yes
54,55,Robust directional forecast,Electronics,"19,40",0
55,56,Customer-focused static array,Home,25.98,no
56,57,Streamlined discrete interface,Home,"332,58",0
57,58,Profound didactic secured line,Toys,€435.54,false
58,59,Innovative modular structure,Books,320.04 EUR,false
59,60,Centralized homogeneous database,Sports,"344,59",true
60,61,Sharable tangible application,Electronics,222.91,1
61,62,Integrated value-added framework,Sports,€117.57,1
62,63,Secured demand-driven interface,Sports,"474,98",0
63,64,Advanced well-modulated knowledgebase,Books,36.04,true
64,65,Inverse intangible encryption,Clothing,€457.31,no
65,66,Stand-alone bi-directional concept,Sports,134.18 EUR,yes
66,67,Profit-focused actuating support,Sports,143.46,1
67,68,Multi-tiered cohesive adapter,Sports,€195.80,yes
68,69,Profound modular matrix,Sports,"268,97",true
69,70,Multi-layered neutral interface,Books,381.08,true
70,71,Assimilated secondary policy,Books,451.35,yes
71,72,Synchronized intermediate info-mediaries,Electronics,261.00,yes
72,73,Front-line multi-state access,Books,113.34,true
73,74,Realigned responsive analyzer,Home,365.44 EUR,yes
74,75,Streamlined dedicated project,Sports,440.14,false
75,76,Intuitive 5thgeneration challenge,Toys,22.04 EUR,1
76,77,Organic tangible conglomeration,Sports,"197,86",yes
77,78,Organized client-server circuit,Electronics,"112,71",true
78,79,Function-based motivating implementation,Home,478.88,1
79,80,Team-oriented background migration,Electronics,466.63,yes
80,81,Decentralized asynchronous standardization,Sports,€262.83,yes
81,82,Networked mission-critical hierarchy,Books,118.80,yes
82,83,Expanded 5thgeneration moderator,Books,€31.04,yes
83,84,Open-source directional matrices,Clothing,€12.35,true
84,85,Exclusive composite encoding,Electronics,355.52 EUR,true
85,86,Exclusive multi-tasking secured line,Books,471.18,1
86,87,Mandatory secondary standardization,Home,407.11,true
87,88,Innovative mission-critical website,Toys,205.37 EUR,yes
88,89,Visionary reciprocal orchestration,Books,172.26 EUR,true
89,90,Profit-focused disintermediate task-force,Sports,331.93,yes
90,91,Extended executive capability,Sports,127.80,1
91,92,Visionary non-volatile access,Clothing,471.18,1
92,93,Virtual 5thgeneration process improvement,Sports,118.27 EUR,1
93,94,Intuitive background utilization,Electronics,€94.53,1
94,95,Progressive solution-oriented conglomeration,Toys,403.57 EUR,no
95,96,Persevering needs-based artificial intelligence,Home,€438.28,true
96,97,Open-source uniform challenge,Home,450.70 EUR,yes
97,98,Quality-focused 6thgeneration utilization,Books,"230,06",true
98,99,Universal client-driven functionalities,Clothing,"340,00",true
99,100,Synchronized value-added help-desk,Sports,264.37 EUR,1

=== products_clean: 100 rows ===

,product_id,name,category,price_eur,in_stock
0,1,Object-based explicit attitude,Clothing,134.94,True
1,2,Configurable upward-trending complexity,Clothing,498.06,True
2,3,Triple-buffered global hierarchy,Books,346.33,True
3,4,Re-contextualized interactive strategy,Electronics,394.82,True
4,5,Multi-tiered bottom-line implementation,Sports,433.18,False
5,6,Business-focused intermediate portal,Home,324.49,True
6,7,Exclusive bifurcated emulation,Toys,314.29,True
7,8,Team-oriented mission-critical info-mediaries,Clothing,53.69,True
8,9,Enhanced systemic challenge,Sports,62.39,True
9,10,Face-to-face regional attitude,Toys,323.37,True
10,11,Team-oriented grid-enabled Graphic Interface,Sports,219.44,True
11,12,Profit-focused leadingedge workforce,Home,419.41,False
12,13,Visionary composite implementation,Home,472.95,False
13,14,Self-enabling mission-critical open system,Books,35.02,True
14,15,Enterprise-wide 5thgeneration middleware,Home,321.07,True
15,16,Exclusive systemic encryption,Clothing,242.00,True
16,17,Virtual clear-thinking capability,Sports,415.80,False
17,18,Grass-roots next generation access,Books,282.80,True
18,19,Adaptive holistic forecast,Clothing,471.99,True
19,20,Extended actuating function,Electronics,282.96,True
20,21,Switchable systematic circuit,Electronics,386.29,True
21,22,De-engineered asymmetric structure,Electronics,145.63,True
22,23,Diverse optimizing instruction set,Home,354.09,True
23,24,Future-proofed well-modulated workforce,Home,293.44,False
24,25,De-engineered asynchronous core,Sports,485.40,True
25,26,Virtual cohesive portal,Books,257.15,True
26,27,Operative didactic toolset,Electronics,208.22,False
27,28,Object-based needs-based matrix,Toys,24.64,True
28,29,Enhanced real-time architecture,Clothing,307.34,True
29,30,Proactive dynamic database,Electronics,38.84,True
30,31,Compatible systemic collaboration,Sports,156.82,True
31,32,Fully-configurable content-based pricing struc...,Sports,237.94,True
32,33,Seamless tangible circuit,Clothing,428.83,False
33,34,Reactive empowering architecture,Toys,180.82,True
34,35,Visionary web-enabled orchestration,Clothing,303.49,True
35,36,Multi-layered attitude-oriented help-desk,Toys,387.28,True
36,37,Progressive even-keeled conglomeration,Clothing,416.57,True
37,38,Switchable non-volatile leverage,Clothing,295.97,True
38,39,Optional zero tolerance open architecture,Clothing,437.34,True
39,40,Re-engineered tertiary open architecture,Books,486.29,True
40,41,Face-to-face clear-thinking neural-net,Electronics,133.52,True
41,42,Reverse-engineered bottom-line utilization,Books,408.18,True
42,43,Optional user-facing interface,Sports,41.64,True
43,44,Multi-layered directional intranet,Toys,109.46,False
44,45,Synergistic next generation infrastructure,Books,203.36,False
45,46,Managed static open system,Clothing,387.09,True
46,47,Enterprise-wide actuating throughput,Clothing,258.20,True
47,48,Business-focused holistic process improvement,Home,171.57,False
48,49,Persistent cohesive protocol,Books,64.31,True
49,50,Up-sized maximized orchestration,Sports,231.90,True
50,51,Multi-layered heuristic collaboration,Books,231.79,True
51,52,Persevering dedicated moratorium,Books,12.68,True
52,53,Polarized national forecast,Sports,305.19,True
53,54,Right-sized demand-driven capacity,Clothing,460.66,True
54,55,Robust directional forecast,Electronics,19.40,False
55,56,Customer-focused static array,Home,25.98,False
56,57,Streamlined discrete interface,Home,332.58,False
57,58,Profound didactic secured line,Toys,435.54,False
58,59,Innovative modular structure,Books,320.04,False
59,60,Centralized homogeneous database,Sports,344.59,True
60,61,Sharable tangible application,Electronics,222.91,True
61,62,Integrated value-added framework,Sports,117.57,True
62,63,Secured demand-driven interface,Sports,474.98,False
63,64,Advanced well-modulated knowledgebase,Books,36.04,True
64,65,Inverse intangible encryption,Clothing,457.31,False
65,66,Stand-alone bi-directional concept,Sports,134.18,True
66,67,Profit-focused actuating support,Sports,143.46,True
67,68,Multi-tiered cohesive adapter,Sports,195.80,True
68,69,Profound modular matrix,Sports,268.97,True
69,70,Multi-layered neutral interface,Books,381.08,True
70,71,Assimilated secondary policy,Books,451.35,True
71,72,Synchronized intermediate info-mediaries,Electronics,261.00,True
72,73,Front-line multi-state access,Books,113.34,True
73,74,Realigned responsive analyzer,Home,365.44,True
74,75,Streamlined dedicated project,Sports,440.14,False
75,76,Intuitive 5thgeneration challenge,Toys,22.04,True
76,77,Organic tangible conglomeration,Sports,197.86,True
77,78,Organized client-server circuit,Electronics,112.71,True
78,79,Function-based motivating implementation,Home,478.88,True
79,80,Team-oriented background migration,Electronics,466.63,True
80,81,Decentralized asynchronous standardization,Sports,262.83,True
81,82,Networked mission-critical hierarchy,Books,118.80,True
82,83,Expanded 5thgeneration moderator,Books,31.04,True
83,84,Open-source directional matrices,Clothing,12.35,True
84,85,Exclusive composite encoding,Electronics,355.52,True
85,86,Exclusive multi-tasking secured line,Books,471.18,True
86,87,Mandatory secondary standardization,Home,407.11,True
87,88,Innovative mission-critical website,Toys,205.37,True
88,89,Visionary reciprocal orchestration,Books,172.26,True
89,90,Profit-focused disintermediate task-force,Sports,331.93,True
90,91,Extended executive capability,Sports,127.80,True
91,92,Visionary non-volatile access,Clothing,471.18,True
92,93,Virtual 5thgeneration process improvement,Sports,118.27,True
93,94,Intuitive background utilization,Electronics,94.53,True
94,95,Progressive solution-oriented conglomeration,Toys,403.57,False
95,96,Persevering needs-based artificial intelligence,Home,438.28,True
96,97,Open-source uniform challenge,Home,450.70,True
97,98,Quality-focused 6thgeneration utilization,Books,230.06,True
98,99,Universal client-driven functionalities,Clothing,340.00,True
99,100,Synchronized value-added help-desk,Sports,264.37,True

=== products_raw: 0 duplicate rows (subset=all columns) ===

Empty DataFrame
Columns: [product_id, name, category, price_eur, in_stock]
Index: []

In [14]:
# Orders

show_all(orders.sort_values("order_id"), "orders")          #sorted
#show_all(orders, "orders")                                 #unsorted

# Duplicates

inspect_duplicates(orders, name="orders")
#inspect_duplicates(orders, subset=["order_id"], name="orders")

NameError: name 'orders' is not defined